spring.application.name=aml

app.debug=true

app.storage.location=${STORAGE_PATH:./uploads}

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@db:1521:orcl
spring.datasource.username=PROYECTO_GSGI
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SECURITY - JWT
security.jwt.secret=uaytsdnfkjenkjbq723gr832bfbqiwbd818d3bdq8wsdb38821dba
security.jwt.admin-expiration-ms=900000
security.jwt.expiration-ms=900000
security.jwt.refreshexpiration-ms=900000



spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=debug
spring.jpa.properties.hibernate.generate_statistics=true